version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: circleci/mongo:4.4.1
        environment:
          MONGO_URI: mongodb://mongo:27017/citibikes-test
    steps:
      - checkout

      - run:
          name: Waiting for MongoDB to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MongoDB && exit 1

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      


      # run lint!
      - run:
          name: lint
          command: npm run lint

      # run test!
      - run:
          name: test
          command: npm run test
